// USER
export const GET_AUTH = 'GET_AUTH';
export const GET_AUTH_SUCCESS = 'GET_AUTH_SUCCESS';
export const UPDATE_AUTH = 'UPDATE_AUTH';
export const DELETE_AUTH = 'DELETE_AUTH';
export const UPDATE_USER_STATUS = 'UPDATE_USER_STATUS';
export const UPDATE_USER_BANNERCOLOR = 'UPDATE_USER_BANNERCOLOR';
export const UPDATE_PROFILE_PHOTO = 'UPDATE_PROFILE_PHOTO';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_ERROR_MESSAGE = 'AUTH_ERROR_MESSAGE';
    // FRIENDS
    export const GET_PENDING_REQUESTS = 'GET_PENDING_REQUESTS';
    export const GET_PENDING_REQUESTS_SUCCESS = 'GET_PENDING_REQUESTS_SUCCESS';
    export const ADD_PENDING_REQUESTS = 'ADD_PENDING_REQUESTS';
    export const ACCEPT_PENDING_REQUESTS = 'ACCEPT_PENDING_REQUESTS';
    export const ACCEPT_PENDING_REQUESTS_SUCCESS = 'ACCEPT_PENDING_REQUESTS_SUCCESS';
    export const DELETE_PENDING_REQUESTS = 'DELETE_PENDING_REQUESTS';
    export const DELETE_PENDING_REQUESTS_SUCCESS = 'DELETE_PENDING_REQUESTS_SUCCESS';
    export const ADD_FRIEND = 'ADD_FRIEND';
    export const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS';
    export const ACCEPT_FRIEND = 'ACCEPT_FRIEND';
    export const ACCEPT_FRIEND_SUCCESS = 'ACCEPT_FRIEND_SUCCESS';
    export const BLOCK_FRIEND = 'BLOCK_FRIEND';
    export const BLOCK_FRIEND_SUCCESS = 'BLOCK_FRIEND_SUCCESS';
    export const UNBLOCK_FRIEND = 'UNBLOCK_FRIEND';
    export const UNBLOCK_FRIEND_SUCCESS = 'UNBLOCK_FRIEND_SUCCESS';
    export const REMOVE_FRIEND = 'REMOVE_FRIEND';
    export const REMOVE_FRIEND_SUCCESS = 'REMOVE_FRIEND_SUCCESS';
    export const FRIENDS_ERROR = 'FRIENDS_ERROR';
    // FRIENDS - SOCKET.IO
    export const IO_UPDATE_FRIEND_STATUS = 'IO_UPDATE_FRIEND_STATUS';
    export const IO_UPDATE_FRIEND_USERNAME = 'IO_UPDATE_FRIEND_USERNAME';
    export const IO_RECEIVE_FRIEND_REQUEST = 'IO_RECEIVE_FRIEND_REQUEST';
    export const IO_ACCEPTED_FRIEND_REQUEST = 'IO_ACCEPTED_FRIEND_REQUEST';
    export const IO_CANCELED_FRIEND_REQUEST = 'IO_CANCELED_FRIEND_REQUEST';
// CHAT
export const GET_CHATS = 'GET_CHATS';
export const GET_CHATS_SUCCESS = 'GET_CHATS_SUCCESS';
export const HIDE_CHAT = 'HIDE_CHAT';
export const SET_CHAT_MESSAGES = 'SET_CHAT_MESSAGES';
export const SET_SELECTED_CHAT = 'SET_SELECTED_CHAT';
export const SET_MESSAGES_READ = 'SET_MESSAGES_READ';
export const SEND_CHAT_MESSAGE = 'SEND_CHAT_MESSAGE'; 
export const SEND_CHAT_MESSAGE_SUCCESS = 'SEND_CHAT_MESSAGE_SUCCESS'; 
export const EDIT_CHAT_MESSAGE = 'EDIT_CHAT_MESSAGE'; 
export const EDIT_CHAT_MESSAGE_SUCCESS = 'EDIT_CHAT_MESSAGE_SUCCESS'; 
export const DELETE_CHAT_MESSAGE = 'DELETE_CHAT_MESSAGE'; 
export const DELETE_CHAT_MESSAGE_SUCCESS = 'DELETE_CHAT_MESSAGE_SUCCESS'; 
export const RESET_CHAT = 'RESET_CHAT';
export const CHAT_ERROR = 'CHAT_ERROR';
// CHAT - SOCKET.IO
export const IO_PUSH_CHAT_MESSAGE = 'IO_PUSH_CHAT_MESSAGE'; 
export const IO_PUSH_LAST_MESSAGE = 'IO_PUSH_LAST_MESSAGE';
export const IO_UPDATE_CHAT_FRIEND_STATUS = 'IO_UPDATE_CHAT_FRIEND_STATUS';
// LOGOUT
export const LOGOUT = 'LOGOUT';